name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    stragegy: 
      matrix:
        go: [1.22, 1.23, 1.24]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version:  ${{ matrix.go }}
      - name: Run tests
        run: go test -v ./...
      - name: Run application
        run: go run math.go